export const codeToName = {
	'ge': 'Genesis',
	'ex': 'Exodus',
	'le': 'Leviticus',
	'nu': 'Numbers',
	'de': 'Deuteronomy',
	'jos': 'Joshua',
	'jg': 'Judges',
	'ru': 'Ruth',
	'1sa': '1 Samuel',
	'2sa': '2 Samuel',
	'1ki': '1 Kings',
	'2ki': '2 Kings',
	'1ch': '1 Chronicles',
	'2ch': '2 Chronicles',
	'ezr': 'Ezra',
	'ne': 'Nehemiah',
	'es': 'Esther',
	'jb': 'Job',
	'ps': 'Psalms',
	'pr': 'Proverbs',
	'ec': 'Ecclesiastes',
	'so': 'Song of Songs',
	'is': 'Isaiah',
	'je': 'Jeremiah',
	'la': 'Lamentations',
	'ek': 'Ezekiel',
	'da': 'Daniel',
	'ho': 'Hosea',
	'jl': 'Joel',
	'am': 'Amos',
	'ob': 'Obadiah',
	'jon': 'Jonah',
	'mi': 'Micah',
	'na': 'Nahum',
	'hk': 'Habakkuk',
	'zp': 'Zephaniah',
	'hg': 'Haggai',
	'zc': 'Zechariah',
	'ml': 'Malachi',
	'mt': 'Matthew',
	'mk': 'Mark',
	'lk': 'Luke',
	'jn': 'John',
	'ac': 'Acts',
	'ro': 'Romans',
	'1co': '1 Corinthians',
	'2co': '2 Corinthians',
	'ga': 'Galatians',
	'ep': 'Ephesians',
	'pp': 'Philippians',
	'co': 'Colossians',
	'1th': '1 Thessalonians',
	'2th': '2 Thessalonians',
	'1ti': '1 Timothy',
	'2ti': '2 Timothy',
	'ti': 'Titus',
	'phm': 'Philemon',
	'he': 'Hebrews',
	'ja': 'James',
	'1pe': '1 Peter',
	'2pe': '2 Peter',
	'1jn': '1 John',
	'2jn': '2 John',
	'3jn': '3 John',
	'jude': 'Jude',
	're': 'Revelation',
};

export const codeToChapterCount = {
	'ge': 50,
	'ex': 40,
	'le': 27,
	'nu': 36,
	'de': 34,
	'jos': 24,
	'jg': 21,
	'ru': 4,
	'1sa': 31,
	'2sa': 24,
	'1ki': 22,
	'2ki': 25,
	'1ch': 29,
	'2ch': 36,
	'ezr': 10,
	'ne': 13,
	'es': 10,
	'jb': 42,
	'ps': 150,
	'pr': 31,
	'ec': 12,
	'so': 8,
	'is': 66,
	'je': 52,
	'la': 5,
	'ek': 48,
	'da': 12,
	'ho': 14,
	'jl': 3,
	'am': 9,
	'ob': 1,
	'jon': 4,
	'mi': 7,
	'na': 3,
	'hk': 3,
	'zp': 3,
	'hg': 2,
	'zc': 14,
	'ml': 4,
	'mt': 28,
	'mk': 16,
	'lk': 24,
	'jn': 21,
	'ac': 28,
	'ro': 16,
	'1co': 16,
	'2co': 13,
	'ga': 6,
	'ep': 6,
	'pp': 4,
	'co': 4,
	'1th': 5,
	'2th': 3,
	'1ti': 6,
	'2ti': 4,
	'ti': 3,
	'phm': 1,
	'he': 13,
	'ja': 5,
	'1pe': 5,
	'2pe': 3,
	'1jn': 5,
	'2jn': 1,
	'3jn': 1,
	'jude': 1,
	're': 22,
};

export const codes = Object.keys(codeToName);
export const codeSet = new Set(codes);
export const ot = new Set(Object.keys(codeToName).slice(0, 39));
export const nt = new Set(Object.keys(codeToName).slice(39));

export const osisToCode = {
	'Gen': 'ge',
	'Exod': 'ex',
	'Lev': 'le',
	'Num': 'nu',
	'Deut': 'de',
	'Josh': 'jos',
	'Judg': 'jg',
	'Ruth': 'ru',
	'1Sam': '1sa',
	'2Sam': '2sa',
	'1Kgs': '1ki',
	'2Kgs': '2ki',
	'1Chr': '1ch',
	'2Chr': '2ch',
	'Ezra': 'ezr',
	'Neh': 'ne',
	'Esth': 'es',
	'Job': 'jb',
	'Ps': 'ps',
	'Prov': 'pr',
	'Eccl': 'ec',
	'Song': 'so',
	'Isa': 'is',
	'Jer': 'je',
	'Lam': 'la',
	'Ezek': 'ek',
	'Dan': 'da',
	'Hos': 'ho',
	'Joel': 'jl',
	'Amos': 'am',
	'Obad': 'ob',
	'Jonah': 'jon',
	'Mic': 'mi',
	'Nah': 'na',
	'Hab': 'hk',
	'Zeph': 'zp',
	'Hag': 'hg',
	'Zech': 'zc',
	'Mal': 'ml',
	'Matt': 'mt',
	'Mark': 'mk',
	'Luke': 'lk',
	'John': 'jn',
	'Acts': 'ac',
	'Rom': 'ro',
	'1Cor': '1co',
	'2Cor': '2co',
	'Gal': 'ga',
	'Eph': 'ep',
	'Phil': 'pp',
	'Col': 'co',
	'1Thess': '1th',
	'2Thess': '2th',
	'1Tim': '1ti',
	'2Tim': '2ti',
	'Titus': 'ti',
	'Phlm': 'phm',
	'Heb': 'he',
	'Jas': 'ja',
	'1Pet': '1pe',
	'2Pet': '2pe',
	'1John': '1jn',
	'2John': '2jn',
	'3John': '3jn',
	'Jude': 'jude',
	'Rev': 're',
};